language: bash
os: linux
arch: arm64-graviton2

sudo: required

addons:
  apt:
    update: true

# Export variables
env:
  global:
    - TF_VERSION=0.14.0
    - TF_INIT_CLI_OPTIONS="-input=false"
    - TF_PLAN_CLI_OPTIONS="-lock=false -input=false"
    - TF_APPLY_CLI_OPTIONS="-auto-approve -input=false"
    - TF_DESTROY_CLI_OPTIONS="-auto-approve -input=false"
    - AWS_DEFAULT_REGION=eu-west-1
    - secure: "XmEq5rxCDZ0txGCe9pt3ZR0WktAJ55FEFH0hT363J7IySoxM8LIDdMGGM1eN03TVI/812WBLpS9DMEmHZsI4u+bypt/lSl87yY2XeXjUnwnH0Xn42nNqFYZMeDVHGBXp8gf5veIi1zsnQfQ6qTeQzPYG0GZEfSe6l3m3rriNbTSh1vt3hcfknC5e3FzM8kVdhCboHljWhRKZSmkbKm4kiaZeq9DIAtzRqTBMsrOYXL36zx395ZBWlm8kgAu4LApndBfSugR9u9q62Rn87p617gRywIAGXkqufdyVAr3dR3kzJg1Dr2cS9aE9fH2Si7YwMaWWIVT7iu5LR+GGwEk8ovK/4En5aRcX42rkOsi71DzgQ/sE7PK+BPvODR4X4SP0+PPqoKb8GPxGfyseK+IXdOEe3psdJ1Er40UjOFxGVj/FSoTgCE2GoopHdF/r6+uaEJHW8AWEDevHm2lp8kFSr2f/SQIdEWg5cPOLKlmwSaQuSauSVsRp/4Ax23Pfyh9hAKT4wap29w8x5gZ4AYnVtmpNrSC5rU1uC+YmO5Jq7EdD+Qaq60T8y0qdmjV73IRVbEUSqznkTbPRjlrVrOzk3D9BaAn8nbo59mQzYSPL3ZoBby0WD34frhDChMWkiLhu5WA7jg2gpAHgv9nZVreJYgGM7tv0/ZShOOEnoVB/DmA="
    - secure: "B3Ylo6GYxGzbrwYXI/zSKItPGTeual0GJ4EN2MvqzI9ENWciVNaH7qVjzHsYPauATjyv++q2KUlDzRUWlqgcF993CV8qhozmOVeCYlEnYvBeJ8WssvxWJyFwY0GS10SmhtuvzD4GXSo8RJIf9wfQxt0sAEVrmLEx62B4v5EvxYV/1aNCInNutyA9ew0OMO3KkVafEJX9Ek/WgT3AuoFiKunItMYk2KgvN03ymPQ1a4VwUB17OL3Dv9gdeRUH6pVeRloAgb9RzjFkDDd6qRy8hI0Hn8X1By4ledwHUA+b9PF8tRys+U1et4f18PlxXOBaaIfznzWTTg3ojCx8R4XPSoDygsLRdziIq/E2yRRzd5IsYZTjLmrJCBpKctGght8sVku59ovArv9g1aG1oalBLoI2ahotdUqBmKUypwbcmuPFMUZk/URl9MvOvrHarDEpENmg0oAEakRaXoPSJGzof3G5AOHtpXtmBT4RtU9DDYHY/9osEwXkBkOhWc8S+rWJhjcT8H+rJ8qxvwMPIMyMhA9u3Usz3F/EznhVEDx4ep9yFI169hQKHRGOtqPoic6ieBGgxTENaHKatJR/sankiNfUCpfqS6HjoDm9KMw6cxCseH8pvwM/Y+Nyz3ug/Jevusw1f6mXrdrBOyQLbDTXdU4KyePAuXnCKIaHHQ/lruA="

before_install:
  - sudo apt-get install software-properties-common -y
  - sudo apt-get install wireguard resolvconf linux-headers-$(uname -r) -y
  - sudo apt-get -y install pwgen #used in Makefile to generate the random admin password 
  - wget https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
  - unzip terraform_${TF_VERSION}_linux_amd64.zip
  - sudo mv terraform /usr/local/bin/
  - rm terraform_${TF_VERSION}_linux_amd64.zip

script:
  - wg genkey | tee /tmp/client_privatekey | wg pubkey > /tmp/client_publickey
  - export TF_VAR_client_public_key=$(cat /tmp/client_publickey)
  - make deploy

after_script:
  - make cleanup
